services:
  app-drf-shop:
    build:
      context: ../../shop
      dockerfile: Dockerfile
    container_name: app-drf-shop
    ports:
      - "8000:8000"
    expose:
      - 8000
    command: "sh /entrypoint.sh"
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes:
      - ../../shop:/shop
      - static_volume:/staticfiles
    networks:
      - ppostgres.network
  nginx:
    build:
      context: ../nginx/
      dockerfile: Dockerfile      
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/mime.types:/etc/nginx/mime.types
      - static_volume:/staticfiles
    depends_on:
      - app-drf-shop
    networks:
      - ppostgres.network

volumes:
  static_volume:

networks:
  ppostgres.network:
    driver: bridge