# Generated by Django 5.1 on 2024-08-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersitem',
            old_name='name',
            new_name='title',
        ),
    ]
