# Generated by Django 5.1 on 2024-08-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_name_ordersitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, verbose_name='Скидка товара'),
        ),
    ]
